### ISSUE TITLE
BQ: Syncing flow context

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#3476]
**Describe the bug**
While syncing flow_contexts for organization 2 in case of maytapi the flow started for a wa group the contact id is missing so it is throwing error while syncing to BQ

**To Reproduce**
```
{"{\"at\": \"2024-04-02T12:54:02.322126Z\", \"error\": \"** (KeyError) key :id not found in: nil\\n\\nIf you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map\\n    (glific 6.0.1) lib/glific/third_party/bigquery/bigquery_worker.ex:664: anonymous fn/3 in Glific.BigQuery.BigQueryWorker.queue_table_data/3\\n    (elixir 1.15.4) lib/enum.ex:2510: Enum.\\\"-reduce/3-lists^foldl/2-0-\\\"/3\\n    (glific 6.0.1) lib/glific/third_party/bigquery/bigquery_worker.ex:654: Glific.BigQuery.BigQueryWorker.queue_table_data/3\\n    (oban 2.17.1) lib/oban/queue/executor.ex:129: Oban.Queue.Executor.perform/1\\n    (oban 2.17.1) lib/oban/queue/executor.ex:74: Oban.Queue.Executor.call/1\\n    (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\\n    (elixir 1.15.4) lib/task/supervised.ex:36: Task.Supervised.reply/4\\n\", \"attempt\": 1}"}
```

**Comment by madclaws** [comment]
Validations for above from schema level will be done in this [PR](https://github.com/glific/glific/issues/3479)
