### ISSUE TITLE
Query getting cancelled due to timeout

### ISSUE THREAD

**Issue by madclaws** [glific/glific#3567]
**Describe the bug**
ERROR 57014 (query_canceled) canceling statement due to user request. This happens due to timeouts mostly and this occurs very frequently.

**Reference**
https://appsignal.com/project-tech4dev/sites/5f480c425ac13f7330101f30/exceptions/incidents/137

***From oban***
Action
```elixir
%{
  "action" => "insert",
  "organization_id" => 165,
  "table" => "contact_histories"
}
```
```js
** (Postgrex.Error) ERROR 57014 (query_canceled) canceling statement due to user request
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
    (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.11.1) lib/ecto/repo/queryable.ex:162: Ecto.Repo.Queryable.one!/3
    (glific 6.0.7) lib/glific/third_party/bigquery/bigquery_worker.ex:170: Glific.BigQuery.BigQueryWorker.insert_max_id/3
    (glific 6.0.7) lib/glific/third_party/bigquery/bigquery_worker.ex:221: Glific.BigQuery.BigQueryWorker.insert_new_records/4
    (oban 2.17.1) lib/oban/queue/executor.ex:129: Oban.Queue.Executor.perform/1
```

**Comment by madclaws** [comment]
This is a very generic issue, need to create issues for specific cases
